services:
  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
  database:
    ports:
      - "5432:5432"
  auth:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
